simulation_compositions:
  simulations:
    - simulation_config: "simulation/house_simulation.yaml"
      mission_configs:
        - "mission/house_mission_lower.yaml"
        - "mission/house_mission_full.yaml"
    - simulation_config: "simulation/large_simulation_out.yaml"
      mission_configs:
        - "mission/large_mission_out.yaml"
    - simulation_config: "simulation/large_simulation_room.yaml"
      mission_configs:
        - "mission/large_mission_room.yaml"
    - simulation_config: "simulation/small_simulation_out.yaml"
      mission_configs:
        - "mission/small_mission_out.yaml"
    - simulation_config: "simulation/small_simulation_room.yaml"
      mission_configs:
        - "mission/small_mission_room.yaml"

  drone_configs:
    - "drone/drone_small.yaml"
    - "drone/drone_large.yaml"

  lidar_configs:
    - "lidar/lidar_long.yaml"
    - "lidar/lidar_short.yaml"

